apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: atingupta2005/currency-conversion:latest
        imagePullPolicy: IfNotPresent
        name: currency-conversion
        env:
          - name: CURRENCY_EXCHANGE_URI
            value: http://currency-exchange
#          - name: SPRING_PROFILES_ACTIVE
#            value: kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: currency-conversion
  name: currency-conversion
  spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8100 #CHANGE
    protocol: TCP
    targetPort: 8100 #CHANGE
  selector:
    app: currency-conversion
  sessionAffinity: None #CHANGE
  type: LoadBalancer